module.exports = {
  rules: {
    'comma-dangle': 0,
    'no-cond-assign': 0,
    'no-console': 1,
    'no-constant-condition': 1,
    'no-control-regex': 0,
    'no-debugger': 1,
    'no-dupe-args': 2,
    'no-dupe-keys': 2,
    'no-duplicate-case': 2,
    'no-empty': 0,
    'no-empty-character-class': 2,
    'no-ex-assign': 0,
    'no-extra-boolean-cast': 0,
    'no-extra-parens': 0,
    'no-extra-semi': 2,
    'no-func-assign': 0,
    'no-inner-declarations': 2,
    'no-invalid-regexp': 2,
    'no-irregular-whitespace': 2,
    'no-negated-in-lhs': 2,
    'no-obj-calls': 2,
    'no-prototype-builtins': 0,
    'no-regex-spaces': 0,
    'no-sparse-arrays': 0,
    'no-unexpected-multiline': 1,
    'no-unreachable': 2,
    'no-unsafe-finally': 2,
    'use-isnan': 2,
    'valid-jsdoc': 0,
    'valid-typeof': 2
  }
};
